"""
Weekly CEO Briefing Generator – Gold Tier.

Generates a comprehensive weekly briefing from:
- Completed tasks (Done/)
- Domain distribution (Personal/ vs Business/)
- Audit logs (Logs/)
- Error rates and system health

Output: Markdown briefing in Briefings/ folder.
"""

from __future__ import annotations

import json
from pathlib import Path
from datetime import datetime, timezone, timedelta
from audit_logger import log_action
from mcp_file_ops import list_tasks, read_task, write_task
from mcp_audit_ops import get_action_summary, get_error_log
from mcp_calendar_ops import get_current_week
from domain_router import get_all_domain_tasks

SERVER_NAME = "ceo_briefing"
BASE_DIR = Path(__file__).resolve().parent
BRIEFINGS_DIR = BASE_DIR / "Briefings"
DONE_DIR = BASE_DIR / "Done"


def count_completed_this_week() -> tuple[int, list[str]]:
    """Count tasks completed in the current week."""
    week = get_current_week()
    week_start = datetime.strptime(week["week_start"], "%Y-%m-%d").replace(tzinfo=timezone.utc)
    done_files = list_tasks(DONE_DIR)
    recent = []

    for name in done_files:
        file_path = DONE_DIR / name
        try:
            mtime = datetime.fromtimestamp(file_path.stat().st_mtime, tz=timezone.utc)
            if mtime >= week_start:
                recent.append(name)
        except OSError:
            continue

    return len(recent), recent


def generate_briefing() -> str:
    """Generate the full CEO weekly briefing as markdown."""
    now = datetime.now(timezone.utc)
    week = get_current_week()
    completed_count, completed_files = count_completed_this_week()
    domain_tasks = get_all_domain_tasks(BASE_DIR)
    audit_summary = get_action_summary(hours=168)  # 7 days
    errors = get_error_log(hours=168)

    # Build task summaries
    task_summaries = []
    for name in completed_files[:10]:  # Cap at 10 for readability
        content = read_task(DONE_DIR / name)
        # Extract first 2 lines of AI Summary if present
        lines = content.split("\n")
        summary_line = ""
        for i, line in enumerate(lines):
            if "## AI Summary" in line or "## Summary" in line:
                if i + 1 < len(lines):
                    summary_line = lines[i + 1].strip()
                break
        task_summaries.append(f"- **{name}**: {summary_line or 'Completed'}")

    briefing = f"""# Weekly CEO Briefing

**Generated:** {now.strftime("%Y-%m-%d %H:%M UTC")}
**Week:** {week['week_start']} to {week['week_end']} (ISO Week {week['iso_week']})
**Day:** {week['current_day']}

---

## Executive Summary

- **Tasks Completed This Week:** {completed_count}
- **Business Tasks Active:** {len(domain_tasks['business'])}
- **Personal Tasks Active:** {len(domain_tasks['personal'])}
- **Total System Actions (7d):** {audit_summary['total_actions']}
- **Errors (7d):** {audit_summary['errors']}
- **System Health:** {'HEALTHY' if audit_summary['errors'] == 0 else 'NEEDS ATTENTION' if audit_summary['errors'] < 5 else 'DEGRADED'}

---

## Completed Tasks

{chr(10).join(task_summaries) if task_summaries else '- No tasks completed this week yet.'}

---

## Domain Distribution

### Business ({len(domain_tasks['business'])} active)
{chr(10).join(f'- {t}' for t in domain_tasks['business'][:5]) or '- No active business tasks.'}

### Personal ({len(domain_tasks['personal'])} active)
{chr(10).join(f'- {t}' for t in domain_tasks['personal'][:5]) or '- No active personal tasks.'}

---

## System Activity Breakdown

| Action | Count |
|--------|-------|
{chr(10).join(f'| {k} | {v} |' for k, v in audit_summary.get('breakdown', {}).items()) or '| No actions recorded | 0 |'}

---

## Errors & Issues

{chr(10).join(f'- [{e.get("timestamp", "?")}] {e.get("server", "?")}.{e.get("action", "?")} — {e.get("details", {}).get("error", "unknown")}' for e in errors[:5]) or '- No errors this week.'}

---

## Recommendations

{"- Review error log and address recurring failures." if audit_summary['errors'] > 0 else "- System operating normally. No action required."}
- {"Consider rebalancing workload — business tasks outnumber personal." if len(domain_tasks['business']) > len(domain_tasks['personal']) * 2 else "Task distribution is balanced."}

---

*Generated by AI Employee Vault — Gold Tier*
"""

    return briefing


def save_briefing() -> str:
    """Generate and save briefing to Briefings/ folder. Returns filename."""
    BRIEFINGS_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc)
    filename = f"CEO_Briefing_{now.strftime('%Y-%m-%d')}.md"
    briefing_content = generate_briefing()
    write_task(BRIEFINGS_DIR / filename, briefing_content)
    log_action(SERVER_NAME, "save_briefing", {"filename": filename})
    print(f"CEO Briefing saved: {filename}")
    return filename


if __name__ == "__main__":
    filename = save_briefing()
    print(f"=== CEO Briefing Generated: {filename} ===")
